function Advanced()
    % CSTR Simulation with Interactive Sliders and Input Boxes
    
    % Figure
    fig = figure('Position', [0 0 1920 1080], 'Name', 'CSTR Simulator');
    
    % Plot Axes
    ax = axes('Parent', fig, 'Position', [0.4 0.15 0.55 0.75]);
    
    % Initial Parameter Values
    params.q = 100;              % Flow Rate (L/min)
    params.CAi = 1;              % Inlet Concentration (mol/L)
    params.Ti = 350;             % Inlet Temperature (K)
    params.V = 100;              % Volume (L)
    params.rho = 1000;           % Density (g/L)
    params.C = 0.239;            % Heat Capacity (J/g K)
    params.deltaHR = -5e4;       % Heat of Reaction (J/mol)
    params.E_R = 8750;           % E/R (K)
    params.k0 = 7.2e10;          % Pre-Exponential Factor (1/min)
    params.UA = 5e4;             % Heat Transfer Coefficient (J/min K)
    params.CA0 = 0.5;            % Initial Concentration (mol/L)
    params.T0 = 350;             % Initial Temperature (K)
    params.Tc1 = 290;            % Cooling Temp 1 (K)
    params.Tc2 = 300;            % Cooling Temp 2 (K)
    params.Tc3 = 305;            % Cooling Temp 3 (K)
    
    % UI Control
    
    % Slider Input Boxes
    sliderHeight = 0.03;
    startY = 0.92;
    spacing = 0.055;
    
    % Flow Rate
    uicontrol('Style', 'text', 'Units', 'normalized', ...
        'Position', [0.02 startY-0*spacing 0.08 0.03], ...
        'String', 'q (L/min):', 'HorizontalAlignment', 'left', 'FontSize', 9);
    uicontrol('Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.10 startY-0*spacing 0.15 sliderHeight], ...
        'Min', 10, 'Max', 200, 'Value', params.q, ...
        'Tag', 'q_slider', 'Callback', @(src,evt) sliderCallback('q'));
    uicontrol('Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.26 startY-0*spacing 0.06 0.03], ...
        'String', num2str(params.q), 'Tag', 'q_edit', ...
        'Callback', @(src,evt) editCallback('q'), 'FontSize', 9);
    
    % CAi
    uicontrol('Style', 'text', 'Units', 'normalized', ...
        'Position', [0.02 startY-1*spacing 0.08 0.03], ...
        'String', 'CAi (mol/L):', 'HorizontalAlignment', 'left', 'FontSize', 9);
    uicontrol('Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.10 startY-1*spacing 0.15 sliderHeight], ...
        'Min', 0.1, 'Max', 5, 'Value', params.CAi, ...
        'Tag', 'CAi_slider', 'Callback', @(src,evt) sliderCallback('CAi'));
    uicontrol('Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.26 startY-1*spacing 0.06 0.03], ...
        'String', num2str(params.CAi), 'Tag', 'CAi_edit', ...
        'Callback', @(src,evt) editCallback('CAi'), 'FontSize', 9);
    
    % Ti
    uicontrol('Style', 'text', 'Units', 'normalized', ...
        'Position', [0.02 startY-2*spacing 0.08 0.03], ...
        'String', 'Ti (K):', 'HorizontalAlignment', 'left', 'FontSize', 9);
    uicontrol('Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.10 startY-2*spacing 0.15 sliderHeight], ...
        'Min', 300, 'Max', 400, 'Value', params.Ti, ...
        'Tag', 'Ti_slider', 'Callback', @(src,evt) sliderCallback('Ti'));
    uicontrol('Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.26 startY-2*spacing 0.06 0.03], ...
        'String', num2str(params.Ti), 'Tag', 'Ti_edit', ...
        'Callback', @(src,evt) editCallback('Ti'), 'FontSize', 9);
    
    % V
    uicontrol('Style', 'text', 'Units', 'normalized', ...
        'Position', [0.02 startY-3*spacing 0.08 0.03], ...
        'String', 'V (L):', 'HorizontalAlignment', 'left', 'FontSize', 9);
    uicontrol('Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.10 startY-3*spacing 0.15 sliderHeight], ...
        'Min', 50, 'Max', 200, 'Value', params.V, ...
        'Tag', 'V_slider', 'Callback', @(src,evt) sliderCallback('V'));
    uicontrol('Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.26 startY-3*spacing 0.06 0.03], ...
        'String', num2str(params.V), 'Tag', 'V_edit', ...
        'Callback', @(src,evt) editCallback('V'), 'FontSize', 9);
    
    % rho
    uicontrol('Style', 'text', 'Units', 'normalized', ...
        'Position', [0.02 startY-4*spacing 0.08 0.03], ...
        'String', 'ρ (g/L):', 'HorizontalAlignment', 'left', 'FontSize', 9);
    uicontrol('Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.10 startY-4*spacing 0.15 sliderHeight], ...
        'Min', 500, 'Max', 1500, 'Value', params.rho, ...
        'Tag', 'rho_slider', 'Callback', @(src,evt) sliderCallback('rho'));
    uicontrol('Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.26 startY-4*spacing 0.06 0.03], ...
        'String', num2str(params.rho), 'Tag', 'rho_edit', ...
        'Callback', @(src,evt) editCallback('rho'), 'FontSize', 9);
    
    % C
    uicontrol('Style', 'text', 'Units', 'normalized', ...
        'Position', [0.02 startY-5*spacing 0.08 0.03], ...
        'String', 'C (J/gK):', 'HorizontalAlignment', 'left', 'FontSize', 9);
    uicontrol('Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.10 startY-5*spacing 0.15 sliderHeight], ...
        'Min', 0.1, 'Max', 1, 'Value', params.C, ...
        'Tag', 'C_slider', 'Callback', @(src,evt) sliderCallback('C'));
    uicontrol('Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.26 startY-5*spacing 0.06 0.03], ...
        'String', num2str(params.C), 'Tag', 'C_edit', ...
        'Callback', @(src,evt) editCallback('C'), 'FontSize', 9);
    
    % deltaHR
    uicontrol('Style', 'text', 'Units', 'normalized', ...
        'Position', [0.02 startY-6*spacing 0.08 0.03], ...
        'String', '-ΔHR (J/mol):', 'HorizontalAlignment', 'left', 'FontSize', 9);
    uicontrol('Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.10 startY-6*spacing 0.15 sliderHeight], ...
        'Min', 1e4, 'Max', 1e5, 'Value', -params.deltaHR, ...
        'Tag', 'deltaHR_slider', 'Callback', @(src,evt) sliderCallback('deltaHR'));
    uicontrol('Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.26 startY-6*spacing 0.06 0.03], ...
        'String', num2str(-params.deltaHR), 'Tag', 'deltaHR_edit', ...
        'Callback', @(src,evt) editCallback('deltaHR'), 'FontSize', 9);
    
    % E/R
    uicontrol('Style', 'text', 'Units', 'normalized', ...
        'Position', [0.02 startY-7*spacing 0.08 0.03], ...
        'String', 'E/R (K):', 'HorizontalAlignment', 'left', 'FontSize', 9);
    uicontrol('Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.10 startY-7*spacing 0.15 sliderHeight], ...
        'Min', 5000, 'Max', 15000, 'Value', params.E_R, ...
        'Tag', 'E_R_slider', 'Callback', @(src,evt) sliderCallback('E_R'));
    uicontrol('Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.26 startY-7*spacing 0.06 0.03], ...
        'String', num2str(params.E_R), 'Tag', 'E_R_edit', ...
        'Callback', @(src,evt) editCallback('E_R'), 'FontSize', 9);
    
    % k0 (log scale)
    uicontrol('Style', 'text', 'Units', 'normalized', ...
        'Position', [0.02 startY-8*spacing 0.08 0.03], ...
        'String', 'k0 (/min):', 'HorizontalAlignment', 'left', 'FontSize', 9);
    uicontrol('Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.10 startY-8*spacing 0.15 sliderHeight], ...
        'Min', 8, 'Max', 12, 'Value', log10(params.k0), ...
        'Tag', 'k0_slider', 'Callback', @(src,evt) sliderCallback('k0'));
    uicontrol('Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.26 startY-8*spacing 0.06 0.03], ...
        'String', num2str(params.k0, '%.2e'), 'Tag', 'k0_edit', ...
        'Callback', @(src,evt) editCallback('k0'), 'FontSize', 9);
    
    % UA
    uicontrol('Style', 'text', 'Units', 'normalized', ...
        'Position', [0.02 startY-9*spacing 0.08 0.03], ...
        'String', 'UA (J/minK):', 'HorizontalAlignment', 'left', 'FontSize', 9);
    uicontrol('Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.10 startY-9*spacing 0.15 sliderHeight], ...
        'Min', 1e4, 'Max', 1e5, 'Value', params.UA, ...
        'Tag', 'UA_slider', 'Callback', @(src,evt) sliderCallback('UA'));
    uicontrol('Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.26 startY-9*spacing 0.06 0.03], ...
        'String', num2str(params.UA), 'Tag', 'UA_edit', ...
        'Callback', @(src,evt) editCallback('UA'), 'FontSize', 9);
    
    % CA0
    uicontrol('Style', 'text', 'Units', 'normalized', ...
        'Position', [0.02 startY-10*spacing 0.08 0.03], ...
        'String', 'CA(0) (mol/L):', 'HorizontalAlignment', 'left', 'FontSize', 9);
    uicontrol('Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.10 startY-10*spacing 0.15 sliderHeight], ...
        'Min', 0, 'Max', 2, 'Value', params.CA0, ...
        'Tag', 'CA0_slider', 'Callback', @(src,evt) sliderCallback('CA0'));
    uicontrol('Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.26 startY-10*spacing 0.06 0.03], ...
        'String', num2str(params.CA0), 'Tag', 'CA0_edit', ...
        'Callback', @(src,evt) editCallback('CA0'), 'FontSize', 9);
    
    % T0
    uicontrol('Style', 'text', 'Units', 'normalized', ...
        'Position', [0.02 startY-11*spacing 0.08 0.03], ...
        'String', 'T(0) (K):', 'HorizontalAlignment', 'left', 'FontSize', 9);
    uicontrol('Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.10 startY-11*spacing 0.15 sliderHeight], ...
        'Min', 300, 'Max', 400, 'Value', params.T0, ...
        'Tag', 'T0_slider', 'Callback', @(src,evt) sliderCallback('T0'));
    uicontrol('Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.26 startY-11*spacing 0.06 0.03], ...
        'String', num2str(params.T0), 'Tag', 'T0_edit', ...
        'Callback', @(src,evt) editCallback('T0'), 'FontSize', 9);
    
    % Temperature sliders
    uicontrol('Style', 'text', 'Units', 'normalized', ...
        'Position', [0.02 startY-12.5*spacing 0.08 0.03], ...
        'String', 'Tc1 (K):', 'HorizontalAlignment', 'left', 'FontSize', 9, ...
        'ForegroundColor', 'b', 'FontWeight', 'bold');
    uicontrol('Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.10 startY-12.5*spacing 0.15 sliderHeight], ...
        'Min', 270, 'Max', 310, 'Value', params.Tc1, ...
        'Tag', 'Tc1_slider', 'Callback', @(src,evt) sliderCallback('Tc1'));
    uicontrol('Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.26 startY-12.5*spacing 0.06 0.03], ...
        'String', num2str(params.Tc1), 'Tag', 'Tc1_edit', ...
        'Callback', @(src,evt) editCallback('Tc1'), 'FontSize', 9);
    
    uicontrol('Style', 'text', 'Units', 'normalized', ...
        'Position', [0.02 startY-13.5*spacing 0.08 0.03], ...
        'String', 'Tc2 (K):', 'HorizontalAlignment', 'left', 'FontSize', 9, ...
        'ForegroundColor', [0 0.5 0], 'FontWeight', 'bold');
    uicontrol('Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.10 startY-13.5*spacing 0.15 sliderHeight], ...
        'Min', 280, 'Max', 320, 'Value', params.Tc2, ...
        'Tag', 'Tc2_slider', 'Callback', @(src,evt) sliderCallback('Tc2'));
    uicontrol('Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.26 startY-13.5*spacing 0.06 0.03], ...
        'String', num2str(params.Tc2), 'Tag', 'Tc2_edit', ...
        'Callback', @(src,evt) editCallback('Tc2'), 'FontSize', 9);
    
    uicontrol('Style', 'text', 'Units', 'normalized', ...
        'Position', [0.02 startY-14.5*spacing 0.08 0.03], ...
        'String', 'Tc3 (K):', 'HorizontalAlignment', 'left', 'FontSize', 9, ...
        'ForegroundColor', 'r', 'FontWeight', 'bold');
    uicontrol('Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.10 startY-14.5*spacing 0.15 sliderHeight], ...
        'Min', 290, 'Max', 325, 'Value', params.Tc3, ...
        'Tag', 'Tc3_slider', 'Callback', @(src,evt) sliderCallback('Tc3'));
    uicontrol('Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.26 startY-14.5*spacing 0.06 0.03], ...
        'String', num2str(params.Tc3), 'Tag', 'Tc3_edit', ...
        'Callback', @(src,evt) editCallback('Tc3'), 'FontSize', 9);
    
    % Initial plot
    updatePlot();
    
    function sliderCallback(param)
        % Get slider value
        slider = findobj('Tag', [param '_slider']);
        val = get(slider, 'Value');
        
        % Special handling for k0 (log scale)
        if strcmp(param, 'k0')
            val = 10^val;
        end
        
        % Update edit box
        edit = findobj('Tag', [param '_edit']);
        if strcmp(param, 'k0')
            set(edit, 'String', num2str(val, '%.2e'));
        else
            set(edit, 'String', num2str(val));
        end
        
        % Update plot
        updatePlot();
    end

    function editCallback(param)
        % Get edit box value
        edit = findobj('Tag', [param '_edit']);
        val = str2double(get(edit, 'String'));
        
        % Validate input
        if isnan(val)
            % Restore previous value
            slider = findobj('Tag', [param '_slider']);
            sliderVal = get(slider, 'Value');
            if strcmp(param, 'k0')
                sliderVal = 10^sliderVal;
                set(edit, 'String', num2str(sliderVal, '%.2e'));
            else
                set(edit, 'String', num2str(sliderVal));
            end
            return;
        end
        
        % Update slider
        slider = findobj('Tag', [param '_slider']);
        minVal = get(slider, 'Min');
        maxVal = get(slider, 'Max');
        
        % Special handling for k0 (log scale)
        if strcmp(param, 'k0')
            logVal = log10(val);
            if logVal >= minVal && logVal <= maxVal
                set(slider, 'Value', logVal);
            else
                % Clamp to range
                if logVal < minVal
                    set(slider, 'Value', minVal);
                    val = 10^minVal;
                else
                    set(slider, 'Value', maxVal);
                    val = 10^maxVal;
                end
                set(edit, 'String', num2str(val, '%.2e'));
            end
        else
            if val >= minVal && val <= maxVal
                set(slider, 'Value', val);
            else
                % Clamp to range
                if val < minVal
                    set(slider, 'Value', minVal);
                    set(edit, 'String', num2str(minVal));
                else
                    set(slider, 'Value', maxVal);
                    set(edit, 'String', num2str(maxVal));
                end
            end
        end
        
        % Update plot
        updatePlot();
    end

    function updatePlot()
        % Get current values from sliders
        p.q = get(findobj('Tag', 'q_slider'), 'Value');
        p.CAi = get(findobj('Tag', 'CAi_slider'), 'Value');
        p.Ti = get(findobj('Tag', 'Ti_slider'), 'Value');
        p.V = get(findobj('Tag', 'V_slider'), 'Value');
        p.rho = get(findobj('Tag', 'rho_slider'), 'Value');
        p.C = get(findobj('Tag', 'C_slider'), 'Value');
        p.deltaHR = -get(findobj('Tag', 'deltaHR_slider'), 'Value');
        p.E_R = get(findobj('Tag', 'E_R_slider'), 'Value');
        p.k0 = 10^get(findobj('Tag', 'k0_slider'), 'Value');
        p.UA = get(findobj('Tag', 'UA_slider'), 'Value');
        p.CA0 = get(findobj('Tag', 'CA0_slider'), 'Value');
        p.T0 = get(findobj('Tag', 'T0_slider'), 'Value');
        p.Tc1 = get(findobj('Tag', 'Tc1_slider'), 'Value');
        p.Tc2 = get(findobj('Tag', 'Tc2_slider'), 'Value');
        p.Tc3 = get(findobj('Tag', 'Tc3_slider'), 'Value');
        
        % Time span
        tspan = [0 10];
        y0 = [p.CA0; p.T0];
        options = odeset('RelTol', 1e-6, 'AbsTol', 1e-8);
        
        % Solve for three temperatures
        try
            [t1, y1] = ode15s(@(t,y) cstr_odes(t, y, p, p.Tc1), tspan, y0, options);
            [t2, y2] = ode15s(@(t,y) cstr_odes(t, y, p, p.Tc2), tspan, y0, options);
            [t3, y3] = ode15s(@(t,y) cstr_odes(t, y, p, p.Tc3), tspan, y0, options);
            
            % Plot
            cla(ax);
            plot(ax, t1, y1(:,1), 'b-.', 'LineWidth', 2, 'DisplayName', sprintf('%.1f K', p.Tc1));
            hold(ax, 'on');
            plot(ax, t2, y2(:,1), 'g--', 'LineWidth', 2, 'DisplayName', sprintf('%.1f K', p.Tc2));
            plot(ax, t3, y3(:,1), 'r-', 'LineWidth', 2.5, 'DisplayName', sprintf('%.1f K', p.Tc3));
            plot(ax, [0 10], [p.CA0 p.CA0], 'k--', 'LineWidth', 1, 'HandleVisibility', 'off');
            hold(ax, 'off');
            
            xlabel(ax, 'Time (min)', 'FontSize', 12);
            ylabel(ax, 'Reactant Concentration (mol/L)', 'FontSize', 12);
            legend(ax, 'Location', 'northeast', 'FontSize', 11);
            grid(ax, 'on');
            xlim(ax, [0 10]);
            ylim(ax, [0 max([max(y1(:,1)), max(y2(:,1)), max(y3(:,1)), 1])]);
            title(ax, 'CSTR Simulation', 'FontSize', 14);
            subtitle('Concentration vs Time', 'FontSize', 14);
        catch ME
            cla(ax);
            text(ax, 0.5, 0.5, sprintf('Error solving ODEs:\n%s', ME.message), ...
                'Units', 'normalized', 'HorizontalAlignment', 'center', 'Color', 'r');
        end
    end

    function dydt = cstr_odes(t, y, p, Tc)
        % Extract variables
        CA = y(1);   % Concentration of A (mol/L)
        T = y(2);    % Temperature (K)
        
        % Calculate reaction rate constant
        k = p.k0 * exp(-p.E_R / T);
        
        % Reaction rate
        r = k * CA;
        
        % Mass balance: dCA/dt
        dCAdt = (p.q/p.V) * (p.CAi - CA) - r;
        
        % Heat balance: dT/dt
        w = p.rho * p.q;  % Mass flow rate (g/min)
        dTdt = (w*p.C*(p.Ti - T) + (-p.deltaHR)*p.V*r + p.UA*(Tc - T)) / (p.V*p.rho*p.C);
        
        % Return derivatives
        dydt = [dCAdt; dTdt];
    end
end